apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app.fullname" . }}-fluentbit
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Parsers_File /fluent-bit/parsers/parsers.conf

    [INPUT]
        Name tail
        # Мы ищем логи контейнеров, в имени которых есть имя нашего приложения
        Path /var/log/containers/*{{ include "django-app.name" . }}*.log
        Parser docker
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [OUTPUT]
        Name loki
        Match kube.*
        # Адрес сервиса Loki в соседнем неймспейсе
        Host loki.monitoring.svc.cluster.local
        Port 3100
        Labels {app="{{ include "django-app.name" . }}"}
